### ISSUE TITLE
Makefile: missing FILE name for target doctor-html

### ISSUE THREAD

**Issue by miwie** [dpmb/dpmb#14]
The `doctor-html` target in `Makefile` misses the file to be processed (`debian-paketmanagement.txt`) and probably should read:

```
doctor-html: $(DEFAULTDEPENDENCIES)
        asciidoctor $(DOCTORDEFAULTOPTIONS) debian-paketmanagement.txt
```

**Comment by xtaran** [comment]
Thanks for the notice. Probably happened while I refactored the `a2x`-based make targets a few days ago.
