### ISSUE TITLE
Fehler bei "Paketcache aufräumen"

### ISSUE THREAD

**Issue by danielfaust** [dpmb/dpmb#31]
Unten auf der Seite steht

Schalter `--clean-on-startup`::
entspricht dem Aufruf `aptitude autoclean`

Schalter `--autoclean-on-startup`::
entspricht dem Aufruf `aptitude clean`

**Comment by xtaran** [comment]
Gefixt. Danke für den Hinweis!

**Comment by danielfaust** [comment]
Gerne! Vielen Dank für das Bereitstellen des Buches.
