### ISSUE TITLE
'docbook-xsl.css' and images should be included in .deb

### ISSUE THREAD

**Issue by miwie** [dpmb/dpmb#7]
Building a Debian package (using 'dpkg-buildpackage -b') works so far, but the file 'docbook-xsl.css' should MHO be included in the package.

**Comment by xtaran** [comment]
Ah, I guess that's related to switching the HTML generation from pure asciidoc to a2x (i.e. asciidoc + docbook). Asciidoc always generates self-contained HTML files. Even pictures are included as `data:` URLs. But I can imagine that docbook isn't so strict about this. Will investigate the issue closer later. Thanks for the notice.

**Comment by miwie** [comment]
Oh yes, even all images are missing in the .deb ;)

**Comment by xtaran** [comment]
Fixed in commit 440e83bbcb349122882ce66aecc84f7ec0d6d1d4
